name: pid_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py310h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.12=h955ad1f_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - awkward==2.9.0
      - awkward-cpp==52
      - contourpy==1.3.2
      - cramjam==2.11.0
      - cycler==0.12.1
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - importlib-metadata==8.7.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mplhep==1.1.0
      - mplhep-data==0.0.5
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.1.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - six==1.17.0
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - uhi==1.0.0
      - uproot==5.7.1
      - vector==1.8.0
      - xxhash==3.6.0
      - zipp==3.23.0
prefix: /home/onok/miniconda3/envs/pid_env
