# Analysis Configuration
analysis:
  directory_name: 'sp_pion_test_epic25100_20260218_N5000'
  analysis_event_type: 'single_particle_pion_events'
  selected_events: 5000
  verbose: true
  plot_verbose: true
  detail_plot_verbose: false
  version: '1.24.2'


vertex_cuts:
  x:
    min: 20
    max: 30
  y:
    min: 20
    max: 30
  z:
    min: 20
    max: 30

# File Paths
file_paths:
  single_particle_pion:
    path: '/home/onok/2025/2025-12/create_events/rec_epic_25100_eicrecon1320_sP_pi-_uniform_N100000_mom_01_5gev.root'
    description: 'single_particle_pion_events'
    number_of_events: 100000
    version: '1.24.2'
    production_method: 'Single particle'
  single_particle_kaon:
    path: '/home/onok/2025/2025-12/create_events/rec_epic_25100_eicrecon1320_sP_k-_uniform_N100000_mom_01_5gev.root'
    description: 'single_particle_kaon_events'
    number_of_events: 100000
    version: '1.24.2'
  single_particle_proton:
    path: '/home/onok/2025/2025-12/create_events/rec_epic_25100_eicrecon1320_sP_p+_uniform_N100000_mom_01_5gev.root'
    description: 'single_particle_proton_events'
    number_of_events: 100000
    version: '1.24.2'

# Branch Names
branches:
  mc:
    mc_branch:
      - 'MCParticles.PDG'
      - 'MCParticles.generatorStatus'
      - 'MCParticles.charge'
      - 'MCParticles.momentum.x'
      - 'MCParticles.momentum.y'
      - 'MCParticles.momentum.z'
      - 'MCParticles.vertex.x'
      - 'MCParticles.vertex.y'
      - 'MCParticles.vertex.z'
      - 'MCParticles.momentumAtEndpoint.x'
      - 'MCParticles.momentumAtEndpoint.y'
      - 'MCParticles.momentumAtEndpoint.z'
      - 'MCParticles.spin.x'
      - 'MCParticles.spin.y'
      - 'MCParticles.spin.z'
      - 'MCParticles.colorFlow.a'
      - 'MCParticles.colorFlow.b'
      - 'MCParticles.parents_begin'
      - 'MCParticles.parents_end'
      - 'MCParticles.daughters_begin'
      - 'MCParticles.daughters_end'
      - 'MCParticles.endpoint.x'
      - 'MCParticles.endpoint.y'
      - 'MCParticles.endpoint.z'
      - 'MCParticles.time'
      - 'MCParticles.mass'

  track:
    segments_branch:
      - 'CentralTrackSegments.length'
      - 'CentralTrackSegments.lengthError'
      - 'CentralTrackSegments.points_begin'
      - 'CentralTrackSegments.points_end'
      - '_CentralTrackSegments_track.index'
      - '_CentralTrackSegments_track.collectionID'
    points_branch:
      - '_CentralTrackSegments_points.position.x'
      - '_CentralTrackSegments_points.position.y'
      - '_CentralTrackSegments_points.position.z'
      - '_CentralTrackSegments_points.momentum.x'
      - '_CentralTrackSegments_points.momentum.y'
      - '_CentralTrackSegments_points.momentum.z'
      - '_CentralTrackSegments_points.pathlength'
      - '_CentralTrackSegments_points.pathlengthError'
      - '_CentralTrackSegments_points.surface'
      - '_CentralTrackSegments_points.system'
      - '_CentralTrackSegments_points.positionError.xx'
      - '_CentralTrackSegments_points.positionError.yy'
      - '_CentralTrackSegments_points.positionError.zz'
      - '_CentralTrackSegments_points.positionError.xy'
      - '_CentralTrackSegments_points.positionError.xz'
      - '_CentralTrackSegments_points.positionError.yz'
      - '_CentralTrackSegments_points.momentumError.xx'
      - '_CentralTrackSegments_points.momentumError.yy'
      - '_CentralTrackSegments_points.momentumError.zz'
      - '_CentralTrackSegments_points.momentumError.xy'
      - '_CentralTrackSegments_points.momentumError.xz'
      - '_CentralTrackSegments_points.momentumError.yz'
      - '_CentralTrackSegments_points.time'
      - '_CentralTrackSegments_points.timeError'
      - '_CentralTrackSegments_points.theta'
      - '_CentralTrackSegments_points.phi'
      - '_CentralTrackSegments_points.directionError.xx'
      - '_CentralTrackSegments_points.directionError.yy'
      - '_CentralTrackSegments_points.directionError.xy'
    vertices_branch:
      - '_CentralTrackVertices_associatedParticles.index'
      - '_CentralTrackVertices_associatedParticles.collectionID'

  tof:
    barrel:
      rec_hits_branch:
        - 'TOFBarrelRecHits.time'
        - 'TOFBarrelRecHits.position.x'
        - 'TOFBarrelRecHits.position.y'
        - 'TOFBarrelRecHits.position.z'
        - 'TOFBarrelRecHits.positionError.xx'
        - 'TOFBarrelRecHits.positionError.yy'
        - 'TOFBarrelRecHits.positionError.zz'
        - 'TOFBarrelRecHits.cellID'
        - 'TOFBarrelRecHits.timeError'
        - 'TOFBarrelRecHits.edep'
        - 'TOFBarrelRecHits.edepError'
      rec_hits_branch_old:
        - 'TOFBarrelRecHit.time'
        - 'TOFBarrelRecHit.position.x'
        - 'TOFBarrelRecHit.position.y'
        - 'TOFBarrelRecHit.position.z'
        - 'TOFBarrelRecHit.positionError.xx'
        - 'TOFBarrelRecHit.positionError.yy'
        - 'TOFBarrelRecHit.positionError.zz'
        - 'TOFBarrelRecHit.cellID'
        - 'TOFBarrelRecHit.timeError'
        - 'TOFBarrelRecHit.edep'
        - 'TOFBarrelRecHit.edepError'
      raw_hits_branch:
        - 'TOFBarrelHits.time'
        - 'TOFBarrelHits.position.x'
        - 'TOFBarrelHits.position.y'
        - 'TOFBarrelHits.position.z'
        - 'TOFBarrelHits.momentum.x'
        - 'TOFBarrelHits.momentum.y'
        - 'TOFBarrelHits.momentum.z'
        - 'TOFBarrelHits.cellID'
        - 'TOFBarrelHits.EDep'
        - 'TOFBarrelHits.pathLength'
        - 'TOFBarrelHits.quality'
      hit_associations_branch:
        - '_TOFBarreHitAssociations_rawHit.index'
        - '_TOFBarreHitAssociations_rawHit.collectionID'
      mc_associations_branch:
        - '_TOFBarrelHits_MCParticle.index'
        - '_TOFBarrelHits_MCParticle.collectionID'
      mc_associations_ver1_24_2_branch:
        - '_TOFBarrelHits_particle.index'
    endcap:
      rec_hits_branch:
        - 'TOFEndcapRecHits.time'
        - 'TOFEndcapRecHits.position.x'
        - 'TOFEndcapRecHits.position.y'
        - 'TOFEndcapRecHits.position.z'
        - 'TOFEndcapRecHits.positionError.xx'
        - 'TOFEndcapRecHits.positionError.yy'
        - 'TOFEndcapRecHits.positionError.zz'
        - 'TOFEndcapRecHits.cellID'
        - 'TOFEndcapRecHits.timeError'
        - 'TOFEndcapRecHits.edep'
        - 'TOFEndcapRecHits.edepError'
      raw_hits_branch:
        - 'TOFEndcapHits.time'
        - 'TOFEndcapHits.position.x'
        - 'TOFEndcapHits.position.y'
        - 'TOFEndcapHits.position.z'
        - 'TOFEndcapHits.momentum.x'
        - 'TOFEndcapHits.momentum.y'
        - 'TOFEndcapHits.momentum.z'
        - 'TOFEndcapHits.cellID'
        - 'TOFEndcapHits.EDep'
        - 'TOFEndcapHits.pathLength'
        - 'TOFEndcapHits.quality'
      hit_associations_branch:
        - '_TOFEndcapHitAssociatedPoints.index'
        - '_TOFEndcapHitAssociatedPoints.collectionID'
      mc_associations_branch:
        - '_TOFEndcapHits_MCParticle.index'
        - '_TOFEndcapHits_MCParticle.collectionID'
      mc_associations_ver1_24_2_branch:
        - '_TOFEndcapHits_particle.index'
